### ISSUE TITLE
서비스 헤더

### ISSUE THREAD

**Issue by Medowhill** [sparcs-kaist/wedalias#3]
지금은 Members by SPARCS 인데

Members of SPARCS
Members for SPARCS

등도 가능할거 같습니다. 아예 다른 구성도 상관 없고요.

일단 이대로 두고 다음 주 정모에서 정해도 괜찮을거 같은데 어떨까요?

**Comment by jwoo0122** [comment]
문구는 여러가지 후보가 있을 거 같아요. 디자인은 통일하는 게 편해보이니 다음 PR 에 포함해 둘게요.

**Comment by Medowhill** [comment]
`Memvers: Management of Electronic Mail via Visualized Editor and Registration for SPARCS`
로 결정한 역두문자어에 따라 뭘로 하든 memvers로 해주세요.
다음 주 정모에서 받아주길 바라며..

**Comment by Medowhill** [comment]
프런트는 https://github.com/sparcs-kaist/memvers-front 로 이동합니다. 해당 프로젝트에 이슈 새로 열겠습니다.
