### ISSUE TITLE
인풋 글자 길이

### ISSUE THREAD

**Issue by Medowhill** [sparcs-kaist/wedalias#4]
현재 passwd 페이지에서 "현재 비밀번호", "새 비밀번호", "새 비밀번호 확인" 길이가 다 다른데 똑같게 맞춰주는게 좋을까요? 다른 페이지에도 동일하게 적용 가능할 문제입니다.

**Comment by jwoo0122** [comment]
디자인 이슈일 수 있을 것 같은데, 인풋 위에 캡션을 달아두는 것도 괜찮다고 생각해요. Material 디자인 input 을 생각하면 됩니다.

**Comment by Medowhill** [comment]
프런트는 https://github.com/sparcs-kaist/memvers-front 로 이동합니다. 해당 프로젝트에 이슈 새로 열겠습니다.
