### ISSUE TITLE
패스워드 조건

### ISSUE THREAD

**Issue by Medowhill** [sparcs-kaist/wedalias#5]
현재는 `8자 이상, 영문 대/소문자 숫자, 특수 문자 사용` 으로 패스워드를 제한 중인데, #2 에서 @samjo-nyang 님께서 언급하신 https://www.theverge.com/2017/8/7/16107966/password-tips-bill-burr-regrets-advice-nits-cybersecurity 에 따라 패스워드 조건을 바꾸는 것이 나아 보입니다.

`16자 이상, 영문 대/소문자만 사용` 은 어떨까요?

**Comment by samjo-nyang** [comment]
저는 그냥 8자 이상 + 쉬운 패스워드 금지 외에 모든 제한을 푸는 것을 추천합니다.
- password manager를 사용한다면 8자리? 10자리 랜덤으로도 충분
- xkcd style의 password 사용하면 16자리 영어 소문자 필요할 수도 있음
- 일부 회원이 이상한 암호 사용하는건 "올바른 교육" + 아이디와 동일한 암호 차단 + 쉬운 패스워드 목록 (password!@#) 같은거 차단으로 해결할 수 있을거라 생각

그리고, 이거 막기 위해서 SPARCS 서버 로그인을 인증서로만 할 수 있게 하자는 프로젝트가 진행되었습니다... (물론 지금은 터짐) https://github.com/sparcs-kaist/pki

**Comment by samjo-nyang** [comment]
아니면 MFA를 도입해보는 것도 좋을 것 같습니다.
https://jonarcher.info/2015/07/hardening-ssh-with-otp-for-2-factor-authentication/

**Comment by Medowhill** [comment]
SSH 접속 및 패스워드 정책은 현 휠장 및 활동하는 휠들의 권한이 맞는 것 같아서 일단 `8자리 이상 & 아이디 포함 금지` 정도로 수정한 뒤, 본 이슈 링크를 현 휠장에게 전달하도록 하겠습니다. 이후에 휠에서 요청이 들어오면 추가적으로 변경하도록 하고요.

**Comment by Medowhill** [comment]
#8

**Comment by Medowhill** [comment]
#9
