### ISSUE TITLE
API 서버 / 프론트 서버 분리

### ISSUE THREAD

**Issue by jwoo0122** [sparcs-kaist/wedalias#7]
이걸 분리해 두면 프론트 작업하기 편할 거 같은데, 작업 가능할 까요? @Medowhill 
지금은 제가 이거 실 서버가 어디에 올라가 있는 지를 몰라서 작업을 하기가 애매한 것 같아요. api 랑 프론트 서버랑 도메인 같이 둘 수 있으면 편할 거 같긴 한데..

아무튼 요지는 프론트 엔드 서버를 분리해두면, 리액트 같은 외부 프레임 워크를 붙여서 사용하기도 편할 것 같습니다. 지금은 도커에 접속해서 원격으로 파일 수정하려니 조금 능률이 떨어지는 느낌이 있네요.

**Comment by Medowhill** [comment]
분리완료했습니다. 앞으로 프런트는 https://github.com/sparcs-kaist/memvers-front 에서 개발하시면 됩니다.
